# Generated by Django 5.0.1 on 2024-01-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('student', models.CharField(max_length=200)),
                ('section', models.CharField(max_length=200)),
            ],
        ),
    ]
